# Generated by Django 5.2 on 2025-04-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPedido',
            new_name='DetallePedido',
        ),
    ]
